apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
extenders:
  - urlPrefix: "http://192.168.1.104:8888"
    filterVerb: "filter"
    prioritizeVerb: "prioritize"
    weight: 1
    enableHTTPS: false
    nodeCacheCapable: false
    ignorable: true
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
