apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-dm-single
  labels:
    app: nginx-single
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 120
  selector:
    matchLabels:
      app: nginx-single
  template: 
    metadata: 
      labels: 
        app: nginx-single 
        version: v1.0.1
    spec: 
      containers: 
        - name: nginx-single 
          image: nginx:alpine 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 250Mi 
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5  
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
---

apiVersion: v1 
kind: Service
metadata: 
  name: nginx-svc-single 
  labels:
    app: nginx-single
spec: 
  ports: 
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP 
  selector: 
    app: nginx-single