version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=employee_db

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
    driver: local
