---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-scheduler-extender
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: spot-scheduler-extender
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spot-scheduler-extender
  template:
    metadata:
      labels:
        app: spot-scheduler-extender
    spec:
      serviceAccountName: spot-scheduler-extender
      tolerations:
      - key: "spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/capacity
                    operator: In
                    values:
                      - spot
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/capacity
                    operator: In
                    values:
                      - on-demand
      containers:
      - name: extender
        image: spot-scheduler-extender:v1
        ports:
        - containerPort: 8888
        imagePullPolicy: IfNotPresent
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1


---
apiVersion: v1
kind: Service
metadata:
  name: spot-scheduler-extender
  namespace: kube-system
spec:
  selector:
    app: spot-scheduler-extender
  ports:
  - port: 80
    targetPort: 8888

